version: '2'

services:

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass olayinka
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  postgres:
    image: 'postgres:9.5'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432' 



  website:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn" --reload "snakeeyes.app:create_app()"
    env_file:
      - .env
    volumes:
      - '.:/snakeeyes'
    ports:
      - '8000:8000'


  celery:
    build: .
    command: --autoreload
    command: celery worker -l info -A snakeeyes.blueprints.contact.tasks   # -l can be debug or info and - A is set to the directory of the task file
    env_file:
      - '.env'
    volumes:
      - '.:/snakeeyes'

volumes:
  redis:
  postgres:
